CONFIG_ZMK_KEYBOARD_NAME="Corne"

CONFIG_ZMK_DISPLAY=y

# Set to improve Bluetooth connectivity.
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Set for secure connection.
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# N-key rollover.
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT=y # Set to enable F13-F24 keys.

# Set to support BitLocker input.
CONFIG_ZMK_USB_BOOT=y

# Bluetooth profiles
# 3 is used for 2 profiles + 1 for the peripheral.
CONFIG_BT_MAX_CONN=3
# Needs to match `CONFIG_BT_MAX_CONN`.
CONFIG_BT_MAX_PAIRED=3

# Eager debouncing https://zmk.dev/docs/features/debouncing#eager-debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=0
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# 7.5ms BLE Polling https://www.youtube.com/watch?v=jWL4nU-vtWs
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6

# USB polling is already set by default to 1000Hz by ZMK.
