manifest:
  remotes:
    - url-base: https://github.com/zmkfirmware
      name: zmkfirmware
    - url-base: https://github.com/urob
      name: urob
    - url-base: https://github.com/kevinpastor
      name: kevinpastor
  projects:
    - remote: zmkfirmware
      name: zmk
      revision: v0.3
      import: app/west.yml
    - remote: urob
      name: zmk-helpers
      revision: main
    - remote: kevinpastor
      name: nice-view-elemental
      revision: develop
  self:
    path: config
